apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: abdelrhmanmasoud/ecommerce:latest
        ports:
        - containerPort: 3000
        #env:
        #- name: AWS_ACCESS_KEY_ID
        #  valueFrom:
         #   secretKeyRef:
          #    name: aws-secrets
          #    key: AWS_ACCESS_KEY_ID
        #- name: AWS_SECRET_ACCESS_KEY
        #  valueFrom:
        #    secretKeyRef:
        #      name: aws-secrets
        #      key: AWS_SECRET_ACCESS_KEY
        #- name: DB_SECRET_NAME
        #  valueFrom:
        #    secretKeyRef:
        #      name: aws-secrets
        #      key: DB_SECRET_NAME
        #- name: REDIS_SECRET_NAME
        #  valueFrom:
        #    secretKeyRef:
        #      name: aws-secrets
        #      key: REDIS_SECRET_NAME
        #- name: APP_SECRET_NAME
         # valueFrom:
         #   secretKeyRef:
         #     name: aws-secrets
         #     key: APP_SECRET_NAME
